### ISSUE TITLE
cond :: [Pair (a -> Boolean) (a -> b)] -> a -> b

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#160]
Similar to [`R.cond`][1] but stricter and simpler (see ramda/ramda#1673). I imagine `R.cond` is used with unary functions the vast majority of the time.

[1]: http://ramdajs.com/docs/#cond

**Comment by benperez** [comment]
:+1: for type signatures
:-1: for mixed-arity lists of functions

**Comment by rjmk** [comment]
Do we prefer `Pair (a -> Boolean) (a -> b)` or `a -> Maybe b`?

**Comment by kedashoe** [comment]
> Do we prefer Pair (a -> Boolean) (a -> b) or a -> Maybe b?

It seems like we might already have defined all the functions we would need to create the conditions to build the `Pair` signature, while with `a -> Maybe b` we would often just be running our same `a -> Boolean` test behind the scenes and than wrapping `b` in a `Just` if it passes.

On the other hand I hope I am missing something cause that is a nice signature :)

Having written that out, maybe `:: [a -> Maybe b] -> a -> b` would be useful as well and fits a slightly different scenario?

**Comment by rjmk** [comment]
Yeah there are some cases where we'll return the `Maybe` directly (e.g. `S.head`), and it could also be more efficient in some cases. But there are lots of questions when we'll have Boolean producing functions. And I think is more of a Boolean handling function. Not least because I think one is probably better off wrapping results in sum types and folding them (e.g. `maybe`, `either`) than using `cond` with Booleans or Maybes

**Comment by davidchambers** [comment]
> Do we prefer `Pair (a -> Boolean) (a -> b)` or `a -> Maybe b`?

The latter is very elegant! You're right, though, that one could instead apply all the functions and fold. At that point the only advantage of `cond` is that it would avoid unnecessary computation.

Perhaps we should not add `cond` at all. I don't use `R.cond` very often.

**Comment by rjmk** [comment]
I wasn't thinking so much of applying all the functions, but rather `cond` seems to be frequently be used as ersatz pattern matching. But I prefer folds to pattern matching anyway, so I would probably just fold

**Comment by scull7** [comment]
Hi @rjmk  and @davidchambers , 

Perhaps this is not the place to ask, but I'm trying to change a project, [Kuss](https://github.com/influentialpublishers/kuss), over to Sanctuary. I have a few `R.cond` statements that I would need to convert.  However, I'm not following the "folding over pattern matching" suggestion enough to implement it.  Would you provide an example?  If there is a better place to ask this question then please direct me to there.

Here is an example `R.cond` statement from my project:
https://github.com/scull7/kuss/blob/couchbase/lib/couchbase/n1ql.js#L14
```javascript
// :: Predicate -> String
const  predicateToWhereEq = R.compose(
  R.join(' AND ')
, R.values
, R.mapObjIndexed(R.cond([
    [ R.equals(null), (v, k) => ` ${k} IS NULL ` ]
  , [ R.is(String), (v, k) => ` ${k} = "${v}" ` ]
  , [ R.T, (v, k) => ` ${k} = ${v} ` ]
  ]))
)
```

**Comment by davidchambers** [comment]
`cond` isn't necessary in this case, since the number and string cases can both be handled with [`toString`][1]. I'll demonstrate one possible approach, broken into several sections.

Preamble:

```javascript
'use strict';

const R = require('ramda');
const {create, env} = require('sanctuary');
const $ = require('sanctuary-def');
```

Specifying an environment which permits values such as `[null, 123, 'abc']`:

```javascript
//    Value :: Type
const Value = $.NullaryType(
  'kuss/Value',
  'https://github.com/influentialpublishers/kuss',
  x => x === null || typeof x === 'number' || typeof x === 'string'
);

const S = create({checkTypes: true, env: env.concat([Value])});
```

Defining our functions:

```javascript
//    formatPair :: Pair String Value -> String
const formatPair = ([k, v]) =>
  `${k} ${v === null ? 'IS NULL' : `= ${S.toString(v)}`}`;

//    specToQuery :: StrMap Value -> String
const specToQuery = S.pipe([S.pairs, S.map(formatPair), S.joinWith(' AND ')]);
```

Using `specToQuery`:

```javascript
specToQuery({foo: null, bar: 123, baz: 'abc'});
// => 'foo IS NULL AND bar = 123 AND baz = "abc"'
```

Feel free to share another example of code currently written in terms of `cond`. :)


[1]: https://sanctuary.js.org/#toString

**Comment by scull7** [comment]
@davidchambers Thank you for the awesome explanation.  From that I can see that I've got a long ways to go in my understanding of the concepts behind sanctuary.js.  In an effort to understand more and hopefully discover a general pattern, I've found several other code examples from some open source repositories that I contribute to and a few interesting use cases from elsewhere.

1. This code takes a date in one of several formats and normalizes it to a [moment.js](http://momentjs.com/) object. https://github.com/influentialpublishers/pimp-my-sql/blob/b98e4e15dc6177457ba88c79856dc3ea3455c194/lib/query.js#L22
```javascript
const dateIsUnix = _.compose(_.equals(0), _.modulo(_.__, 1));

const momentFromString = (date) => moment(new Date(date));

const momentFromDate = _.cond([
  [ _.isNil,         moment ]
, [ moment.isMoment, _.identity ]
, [ dateIsUnix,      moment.unix ]
, [ _.T,             momentFromString ]
]);
```
2. Here we validate that a given value matches an expected type shape. https://github.com/influentialpublishers/jigawatt/blob/8c9e445245119b8bd8351eea44629977d54b7d2b/lib/validate.js#L36
```javascript
// I've excluded the external functions for brevity's sake. 
const typeCheck = (middleware) => middleware.forEach((mw, index) => {
  return _.cond([
    [ Helper.isObject,  _.always(null) ]
  , [ Array.isArray,    typeCheckArray(index) ]
  , [ _.T,              () => throwMiddlewareNotObject(index) ]
  ])(mw);
});
```
3. This is an interesting use case from [Influential's](https://influential.co) internal dashboard application. It takes an object with optional properties and retrieves a single value from a property which exists in a given priority list of property names. This is very useful when dealing with information originating from non-versioned 3rd party APIs. https://goo.gl/AQ7wqC
```javascript
const propFallback = R.compose(
  R.cond
, R.append([ R.T, R.always(null) ])
, R.map((x) => [ R.has(x), R.prop(x) ])
)

propFallback([ 'foo', 'bar' ])({ foo: 'fuzz', bar: 'buzz' })
```
4. Finally, here are two examples of determining an object's "status" based upon the internal state of that object.   
```javascript
const parseStatus = R.cond([
  [R.propEq('is_blessed', 0), R.always('draft')],
  [R.compose( R.gt(Moment().unix()), R.prop('run_end_date') )
    , R.always('ended')],
  [R.propEq('is_blessed', 1), R.always('active')],
  [R.T                      , R.always('draft')]
])

const mergeStatus = (opportunity) => R.compose(
  R.merge(opportunity)
, R.cond([
    [R.always(checkIfCompleted(opportunity)),                           R.always({status: STATUS_COMPLETED})]
  , [R.compose(notNil, R.path(['submitted_rate'])),                     R.always({status: STATUS_ACCEPTED})]
  , [R.compose(notNil, R.path(['email_send', 'sent'])),                 R.always({status: STATUS_SENT})]
  , [R.T,                                                               R.always({status: STATUS_DRAFT})]
  ])
)(opportunity)
```

I don't expect answers to everything, but as I said, I hope to learn a general pattern or approach that fits more in line with the "fold over pattern matching" idea.  

Also, perhaps this would make for a good start to a sanctuary.js cook book? So that others may gain from this discussion without having to search specifically for it.  Prior art... [Ramda Cookbook](https://github.com/ramda/ramda/wiki/Cookbook)

Thank you again for taking the time to help.

**Comment by davidchambers** [comment]
1.  I suggest working with consistently typed values. I'm not clever enough to reason about functions which operate—in an ad hoc fashion—on four different data types. ;)

2.  Again, I suggest working with consistently typed values.

3.  I suggest this approach:

    ```javascript
    //    findSatisfactory :: (Any -> Boolean) -> Array String -> StrMap a -> Maybe a
    const findSatisfactory = S.curry3((pred, keys, map) =>
      S.reduce(m => k => m.isJust ? m : S.get(pred, k, map), S.Nothing, keys)
    );

    findSatisfactory(S.is(String), ['foo', 'bar'], {});
    // => Nothing

    findSatisfactory(S.is(String), ['foo', 'bar'], {bar: 'buzz'});
    // => Just('buzz')

    findSatisfactory(S.is(String), ['foo', 'bar'], {bar: 'buzz', foo: 'fuzz'});
    // => Just('fuzz')
    ```

4.  I suggest using nested ternary expressions:

    ```javascript
    //    parseStatus :: Moment -> { is_blessed :: Integer, run_end_date :: Integer } -> Status
    const parseStatus = S.curry2((now, r) =>
      r.is_blessed === 0          ? 'draft' :
      now.unix() > r.run_end_date ? 'ended' :
      r.is_blessed === 1          ? 'active' :
      /* otherwise */               'draft'
    );
    ```

    Note that the Moment value representing the current time is now provided as an argument. In order to write functions which are deterministic (and thus easy to test) we must avoid reading values from the outside world. :)

**Comment by scull7** [comment]
Thank you for looking over everything and giving thoughtful explanations.  #3 really helps to understand how folding can replace a pattern matching conditional; and #4 is beautiful, the current implementation is certainly over complicated, thank you.  

I know that you stated that #1 and #2 should just deal with consistently typed data, but then what is a good approach to validating and/or transforming data coming in from the outside world, which is what those 2 functions are doing.  I'm guessing an approach similar to this: http://origamitower.github.io/folktale/en/folktale.data.validation.html using `S.Either`, is that going in the right direction?

**Comment by davidchambers** [comment]
When dealing with inconsistent data from the outside world it is often necessary, as you suggest, to write functions with types such as `Any -> Moment` or `Any -> Array Integer`. Functions such as [`get`][1] and [`gets`][2] make Sanctuary well suited to this task.

In the case of `momentFromDate` (which is misleadingly named), I suggest avoiding `cond`:

```javascript
//    toMoment :: Moment -> Any -> Moment
const toMoment = S.curry2((fallback, x) =>
  x == null           ? fallback :
  moment.isMoment(x)  ? x :
  Number.isInteger(x) ? moment.unix(x) :
  /* otherwise */       moment(new Date(x))
);
```

By requiring the fallback Moment value to be provided as an argument, `toMoment` is deterministic.


[1]: https://sanctuary.js.org/#get
[2]: https://sanctuary.js.org/#gets
