### ISSUE TITLE
encase return Left/Nothing when null / undefined / NaN

### ISSUE THREAD

**Issue by JAForbes** [sanctuary-js/sanctuary#241]
I'm finding that despite using encase, I'm still encountering nulls (they are pervasive in JS libraries).  Would it to possible to make encase even stricter, and return Left/Nothing if the result is null, undefined or NaN?

**Comment by joneshf** [comment]
This suggest sounds sane from a consistency standpoint. We have `toMaybe` which does something like this null stuff. And `toMaybe` looks very similar to what an `encase0` would look like:

```js
encase3 :: (a -> b -> c -> d) -> (a -> b -> c -> Maybe d)
encase2 :: (a -> b -> c)      -> (a -> b -> Maybe c)
encase  :: (a -> b)           -> (a -> Maybe b)
toMaybe :: (a?)               -> (Maybe a)
```

I think this sounds like a good idea, but I think others probably have a better idea of whether or not it actually is.

**Comment by davidchambers** [comment]
I'm of the opinion that exceptions and "bogus" values should be handled separately for maximum flexibility and ease of understanding. Consider the following functions:

```haskell
-- ! indicates a function which may raise an exception
f :: String -> Integer !
g :: String -> Nullable Integer
h :: String -> Nullable Integer !
```

We can create safe versions of these functions using [`encase`][1], [`toMaybe`][2], or both:

```javascript
//    fʹ :: String -> Maybe Integer
const fʹ = S.encase(f);

//    gʹ :: String -> Maybe Integer
const gʹ = S.compose(S.toMaybe, g);

//    hʹ :: String -> Maybe Integer
const hʹ = S.compose(R.chain(S.toMaybe), S.encase(h));
```

From the definition of `hʹ` we can infer that `h` may raise an exception or return `null`/`undefined`. Were we to provide a function which handled both failure conditions, the definition of `hʹ` could become `S.<name>(h)`, but the reader would then wonder whether `h` throws, returns `null`, or both.

Additionally, some functions can legitimately return `null`. The result of `JSON.parse('null')`, for example, is `null`, so `S.encase(JSON.parse, 'null')` should evaluate to `Just(null)`.

While `encase` and `toMaybe` have a common goal, they are solving different problems. I suggest we keep them separate.

@JAForbes and @joneshf, do you find these points compelling?


[1]: https://sanctuary.js.org/#encase
[2]: https://sanctuary.js.org/#toMaybe

**Comment by JAForbes** [comment]
@davidchambers your point is compelling! :)

But I think I disagree.  I think `S.encase(JSON.parse, 'null')` should evaluate to `Nothing`
Functions that legitimately return null are probably attempting to signal something semantically equivalent to `Nothing` anyway.

I am all for composing granular functions though.  Maybe I am not considering some genuine use cases for null?

But I do like your composition example.  It is certainly easy to do which is comforting.

**Comment by davidchambers** [comment]
> Functions that legitimately return null are probably attempting to signal something semantically equivalent to `Nothing` anyway.

Absolutely. `toMaybe` is useful in these cases.

`JSON.parse('null')` is not one of these cases, though. `JSON.parse` throws if applied to a string which is not valid JSON, but `'null'` *is* valid:

```javascript
JSON.parse('null');
// => null

JSON.parse('undefined');
// ! SyntaxError: Unexpected token u
```

Admittedly, `null` is unlikely to be the result we're hoping to see. In order to make the result well typed we would need to filter it. This is the reason [`parseJson`][1] takes a type representative as its first argument (and will take a predicate instead once #191 is merged).

The current definition of `encase` is very clear, as the function does only one thing. I don't think we should get into the business of guessing which values are "bogus". `null`? Sure. `undefined`? I'd say so. `NaN`? *Probably.* `-1`? *Who knows?*

The nice thing is that the Maybe type supports `filter` and `reject`. For example:

```javascript
> R.reject(Number.isNaN, S.Just(NaN))
Nothing
```

I'll close this issue, but feel free to comment further.


[1]: https://sanctuary.js.org/#parseJson
