### ISSUE TITLE
R.props

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#320]
I found myself needing to do this on an object of unknown object of dubious origin and couldn't find an elegant way to do it in Sanctuary. I ended up doing this but it would have been nice to use something similar to `S.gets`:

```js
compose(R.map(toMaybe), R.props(['a', 'b']);
```

**Comment by davidchambers** [comment]
Here's one reasonable approach:

```javascript
> S.map(S.get(S.is(Number), S.__, {a: 42, b: null, c: 0}), ['a', 'b'])
[Just(42), Nothing]

> (o => S.map(S.get(S.is(Number), S.__, o), ['a', 'b']))({a: 42, b: null, c: 0})
[Just(42), Nothing]
```

**Comment by svozza** [comment]
Yep, that'll do the trick!

**Comment by safareli** [comment]
>Although it's a shame we aren't able to go pointfree now

You can if you really want 😄 


```js
> const obj = {a: 42, b: null, c: 0}
> const keys = ['a', 'b']
> S.map(S.get(S.is(Number), S.__, obj), keys)
[Just(42), Nothing]
> (o => S.map(S.get(S.is(Number), S.__, o), keys))(obj)
[Just(42), Nothing]
```

If we take a look at `S.map(S.get(S.is(Number)), keys)` it is an array of functions waiting for our `obj` to return `Maybe Numbers` so we need to map over it using function of type: `(SomeObj -> [Maybe Number]) -> [Maybe Number]`. we could use `A :: (a -> b) -> a -> b` but it's not quite what we want, it needs a little of a "massage" with `flip` (`flip(A) :: a -> (a -> b) -> b`):

```js
S.map(
  S.flip(S.A)(obj),
  S.map(S.get(S.is(Number)), keys)
)
```

Now to move `obj` out, we need to flip outer `map`:
```js
S.flip(S.map)(
  S.map(S.get(S.is(Number)), keys),
  S.flip(S.A)(obj)
)
```

Last step will be to use compose or pipe:
```js
const f = S.flip(S.map)(S.map(S.get(S.is(Number)), keys))
const g = S.flip(S.A)
compose(f, g)(obj)
```

Also I think you can use `__` instead of `flip`:
```js
const f = S.map(S.__, S.map(S.get(S.is(Number)), keys))
const g = S.A(S.__)
compose(f, g)(obj)
```

**Comment by davidchambers** [comment]
[`S.T`][1] is the "flipped" version of [`S.A`][2]. :)


[1]: https://sanctuary.js.org/#T
[2]: https://sanctuary.js.org/#A
