### ISSUE TITLE
branch naming convention

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#341]
I created Sanctuary while working at Plaid. At Plaid I instituted a branch naming convention to give people on the team the freedom to `--force` push without ever inadvertently overwriting someone else's work. I've continued to use this convention for the Sanctuary projects. The format is as follows:

             dc-git-date
    author's ==|======== branch
    initials   |         identifier
               |
               separator
               (hyphen)

I very much appreciate the benefits such a convention provides, but there's room to improve the details. Problems with the current format:

  - initials are not guaranteed to be unique;
  - initials are not a good way to identify people we know by GitHub username rather than by legal name; and
  - hyphen (`-`) does not make a good namespace separator as it's also used to separate words in the branch identifier.

I propose this format:

             davidchambers/git-date
    author's =============|======== branch
    username              |         identifier
                          |
                          separator
                          (slash)

GitHub usernames are guaranteed to be unique. There's no need to remember a mapping from initials to GitHub username. Slash (`/`) is commonly used to separate components in hierarchies.

Does this sound good?

I also propose that those with commit access to Sanctuary repositories make feature branches in these rather than in personal forks. Are there any downsides to doing so?

**Comment by svozza** [comment]
I actually thought the naming convention was to use your Github username for some reason! This sounds perfectly reasonable to me. The only reason I've been using my Sanctuary fork was habit, I've been committing directly to any of the new repos.

**Comment by rjmk** [comment]
Sounds good! The only potential issue I see is guiding us too strongly towards each branch having only one committer. Of course, it doesn't *stop* us having more collaborative branches, but it might set a certain framing.

On the other hand, maybe collaborating via multiple committers (as opposed to comments &c) is not a good idea, and so that framing will be useful

**Comment by davidchambers** [comment]
I think this helps even when collaborating, Rafe. I know *never* to `--force` push to `rjmk/...`. I also know that you are free to do so, so I *must* communicate with you before pushing commits to one of your branches. We could then agree to treat the branch as append-only.

**Comment by rjmk** [comment]
Cool! Works for me :)

**Comment by Avaq** [comment]
Seems reasonable. I guess it entails describing the practice in `CONTRIBUTING.md`.

**Comment by kedashoe** [comment]
Is this to make it easier to review other members work? It doesn't really change anything (as far as making it easier/simpler) for ones own PRs?

> Are there any downsides to doing so?

Maybe because it is different from how non-members submit pull requests? So now there are two things people need to know about and as a member I have a different work flow when reviewing pull requests depending on who submitted it (if I am understanding the proposal correctly).

And personally I just feel more comfortable working in my own fork :) Don't have to worry about accidentally pushing things that aren't meant for the public repo.

**Comment by davidchambers** [comment]
You're right, Kevin, that creating feature branches in this repository rather than in forks wouldn't change the workflow. Now that GitHub grants those with commit access to a parent repository the ability to update pull request branches in its forks (unless pull request submitters explicitly opt out), there really is no difference.

> And personally I just feel more comfortable working in my own fork :)

I'm 100% okay with you continuing to do so. :)

As for there being two ways to do things, this is already the case as I don't have my own forks of the Sanctuary repositories. ;)

It seems there are no objections to the proposed branch naming convention. Let's adopt it. Those with commit access to Sanctuary projects who prefer to create branches in the parent repositories should use their `username/` namespace; those who prefer to work in forks needn't change anything.

**Comment by kedashoe** [comment]
cool, sounds good!

**Comment by davidchambers** [comment]
I've started prefixing my branch names with `davidchambers/`. Feel free to do the same (with your GitHub username).
