### ISSUE TITLE
Type representation for generator functions

### ISSUE THREAD

**Issue by arsaniwilliam** [sanctuary-js/sanctuary#373]
executing this in the repl
```javascript
S.prop('a', {a : function*(){return 12}} )
```
results in
```
TypeError: Type-variable constraint violation

prop :: Accessible a => String -> a -> b
                                       ^
                                       1

1)  function* (){return 12} ::

Since there is no type of which all the above values are members, the type-variable constraint has been violated.
```
It used to work before, now it's breaking.  
Is there a type representation for generator functions? (is this even the issue? i'm not completely sure)
I'm currently using the latest version of ES6

**Comment by davidchambers** [comment]
The problem is that `function*() { return 12; }` is not a member of any of the types in [`S.env`][1].

One solution is to update the definition of [`$.AnyFunction`][2]. The current definition is essentially:

```javascript
x => Object.prototype.toString.call(x) === '[object Function]'
```

Generator functions do not satisfy this predicate. We could use this predicate instead:

```javascript
x => typeof x === 'function'
```

If you're interested, @arsaniwilliam, you could submit a pull request for sanctuary-def. Specifically, you would need to update [`AnyFunction`][3].


[1]: https://sanctuary.js.org/#env
[2]: https://github.com/sanctuary-js/sanctuary-def/tree/v0.9.0#AnyFunction
[3]: https://github.com/sanctuary-js/sanctuary-def/blob/v0.9.0/index.js#L431-L434

**Comment by arsaniwilliam** [comment]
@davidchambers  Thanks for the explanation.
I will submit a pull request soon.

**Comment by arsaniwilliam** [comment]
merge request: github/sanctuary-js/sanctuary-def#131  
1 problem though.. I added a line in the test to check that generator functions pass as well, but the es3 linter fails to parse the `*` .. not sure how to get around that.

**Comment by gabejohnson** [comment]
@arsaniwilliam see this SO [question](http://stackoverflow.com/questions/23096064/how-can-i-feature-detect-es6-generators)

**Comment by davidchambers** [comment]
Thank you for the pull request, Arsani! :)

**Comment by arsaniwilliam** [comment]
My pleasure! This is my first public contribution on github and i'm glad it's to Sanctuary :)

**Comment by arsaniwilliam** [comment]
So here's a thought.. at some point should we make the distinction between "normal" functions and Generator function types?

**Comment by davidchambers** [comment]
We could define `$.AnyGeneratorFunction`, but for now I'm happy to let users define this type in their own code. I'm not sure yet whether such a type is useful.

**Comment by davidchambers** [comment]
```console
$ npm install sanctuary@0.13.2
$ node --print 'require("sanctuary").prop("a", {a: function*() { return 12; }})'
[Function: a]
```
