### ISSUE TITLE
Composing monadic and non monadic functions

### ISSUE THREAD

**Issue by mfidemraizer** [sanctuary-js/sanctuary#458]
Hi!

I've some simple question. I've found that some functions won't return monads (f.e. `joinWith`).

So, I understand that when chaining functions in a composition, I'm expected to use `chain` this way?:

```javascript
compose([
     chain(fn3),
     chain(arr => of(Either, joinWith(", ", arr))),
     chain(fn2)
], fn1())
```

Am I missing something? What's the expected approach to solve this scenario?

**Comment by davidchambers** [comment]
To apply a function which never fails within the context of a structure (e.g. Either) one should use `map` rather than `chain`. The second transformation in the composition should be `map(joinWith(', '))`.

By using both `chain` and `map` it's possible to compose operations which may fail with operations which always succeed. :)

**Comment by mfidemraizer** [comment]
I was going to give my example using `map`, but it can't be used:

```javascript
compose([
     chain(fn3),
     map(joinWith(", ")),
     chain(fn2)
], fn1())
```

See that `fn2` may be `Right([1, 2, 3])` so `joinWith(",")` would receive an array item instead the full array.

Am I mistaken? :D

**Comment by mfidemraizer** [comment]
Yes, I'm mistaken, because `map` receives `Right([1, 2, 3])`.

Nevermind :D

**Comment by mfidemraizer** [comment]
My issue was with a custom `composeK`:

```
composeK([
     fn3,
     map(joinWith(", ")),
     fn2
], fn1())
```

In that code sample, map would receive the array *as is* returned by `fn2`.

It seems like that turning the code less verbose with implicit chains makes things harder when chaining functions that never fail, or may fail or return `Nothing`.

**Comment by davidchambers** [comment]
> It seems like that turning the code less verbose with implicit chains makes things harder when chaining functions that never fail, or may fail or return `Nothing`.

Well stated. For this reason I've rarely found [`R.composeK`][1] and [`R.pipeK`][2] to be useful.

My advice is to stick with

```javascript
pipe([
  chain(...),
  chain(...),
  chain(...),
])
```

even though it's a bit repetitive, as it's easier to modify this code than to modify the equivalent code expressed in terms of `pipeK`.


[1]: http://ramdajs.com/docs/#composeK
[2]: http://ramdajs.com/docs/#pipeK

**Comment by mfidemraizer** [comment]
I see. 

About your advise about using `pipe`, I thought that `compose` would be more readable (I know that this is subjective...) when you do something like my sample on which you call the composition giving some function return value as argument.

In the other hand, if the whole composition isn't going to be called directly, it seems like `pipe` is better.

Well, thank you for your effort!

**Comment by davidchambers** [comment]
Keep in mind that [`S.compose`][1] takes exactly two function arguments, so in the Sanctuary world [`S.pipe`][2] is the easiest way to compose more than two functions. `S.pipe` applies the functions from left to right, because my subjective view is that code should be read top-to-bottom rather than bottom-to-top. :)


[1]: https://sanctuary.js.org/#compose
[2]: https://sanctuary.js.org/#pipe

**Comment by mfidemraizer** [comment]
Hey, I see... you're right, I should read the docs carefully. Thank you again.
