### ISSUE TITLE
Question/Feature Request: Does sanctuary need to implement transducer proto?

### ISSUE THREAD

**Issue by blackxored** [sanctuary-js/sanctuary#478]
Bare with me since I'm new to the library. Coming from ramda I'm wondering if it Sanctuary implements (via Foldable but unlikely) or should implement the [transducer protocol](https://github.com/cognitect-labs/transducers-js#the-transducer-protocol) or there are other ways of skipping the intermediates with sanctuary.

**Comment by davidchambers** [comment]
> Bare with me since I'm new to the library.

Welcome to the Sanctuary community. :wave:

New voices and viewpoints are always appreciated.

We have chosen not to support transducers for several reasons:

  - doing so would significantly increase the implementation complexity of many Sanctuary functions;
  - doing so would make the documentation of the affected functions more complex;
  - doing so would—I think—violate the type signatures we hold dear; and
  - the Ramda community has not embraced transducers (ramda/ramda#1958).

In many ways Sanctuary is Ramda v2. We have been able to incorporate good ideas from Ramda while iteratively clarifying and simplifying the library to prevent it from collapsing under its own weight.

Sanctuary is more consistent and more principled than Ramda, but most importantly it is much simpler. I just responded to ramda/ramda#2442, so the different “lift” functions provided by the libraries spring to mind as an example of differing complexity levels. Here are the type signatures:

```haskell
R.lift :: (*... -> *) -> ([*]... -> [*])

S.lift2 :: Apply f => (a -> b -> c) -> f a -> f b -> f c
S.lift3 :: Apply f => (a -> b -> c -> d) -> f a -> f b -> f c -> f d
```

The Ramda signature tells us very little about what `R.lift` does or how we might use it.

The [Ramda][1] implementation is quite involved, whereas the [Sanctuary][2] one is trivial.

I will be very excited if someone finds a way to get the benefits of transducers without the downsides.


[1]: https://github.com/ramda/ramda/blob/v0.25.0/source/liftN.js
[2]: https://github.com/sanctuary-js/sanctuary-type-classes/blob/v8.0.0/index.js#L1653-L1671

**Comment by Avaq** [comment]
> doing so would—I think—violate the type signatures we hold dear -- @davidchambers 

I did some looking into this, and it seems transducers cannot be lawful Functors. Therefore, I think it's a bad idea to include it in `S.map`, as it would break the type signature:

```diff
-map :: Functor f => (a -> b) -> f a -> f b
+map :: Functor f => (a -> b) -> ((f a -> f b) | (Reducer s a r -> Reducer t b r))
```

I had to invent new syntax just to make that signature. That's not to say that we *can't* implement transducers, they would just have to live in their own namespace, for example in a package called `sanctuary-transducers`. The signature without trying to mix it with `map` is fine:

```hs
tmap :: (a -> b) -> Reducer s a r -> Reducer t b r
```

But I believe there is already a number of libraries which do exactly that. The benefit of a sanctuary-made one would be nothing besides stricter input type checking. I personally don't use transducers often enough to trade my time for the gain of this small benefit.

> or there are other ways of skipping the intermediates with sanctuary -- @blackxored 

You will have to do it yourself. Though I would make sure you need to, for example if you have identified a performance issue related to intermediate structures.

For `map(f)`-`map(g)` kind of situations it's as easy as changing it to `map(compose(g, f))`. For cases where you have different steps, like `map`-`filter`-`map`, you'll have to write a monolithic `reduce` function. But since you're trading code maintainability for optimised performance at this point, you might as well go for an imperative loop.

Or if the issue is memory related, you could consider using a Stream instead. Sanctuary `map` etc. work with Fantasy Land Streams, such as [most](https://github.com/mostjs/core).

----

**Additional thought:** I wouldn't advise it, but if we were to support transducers, in theory the *implementation* of `map` *could* make use of transducers, for example:

```js
Array$prototype$map(f, xs){ return intoArray(tmap(f), xs) }
Object$prototype$map(f, o){ return intoObject(tmap(f), o) } //both build on tmap
```

The point of that would be to embrace the promise of transducers: that we only have to implement `map` once, and we can reuse it (as shown) across multiple data structures using the corresponding adapters.

**Comment by davidchambers** [comment]
I'm intrigued by your additional thought, Aldwin. :)

**Comment by davidchambers** [comment]
<https://sanctuary.js.org/#transducers>

I'm happy to resume this discussion at any point in the future.
