### ISSUE TITLE
Is String Foldable?

### ISSUE THREAD

**Issue by gautaz** [sanctuary-js/sanctuary#493]
Hello,

I was wondering why a character string is not considered as a Foldable.
AFAIU, a character string could be reduced character by character.

Can someone give me more insight on this point ?

**Comment by davidchambers** [comment]
Setting aside contradictions which arise if one treats `String` as shorthand for `Array Char`, `String` cannot satisfy the requirements of [Foldable][1] because we need a value of type `Foldable f => f a` *for any type `a`*, but the inner type is fixed (to `Char`).


[1]: https://github.com/fantasyland/fantasy-land#foldable

**Comment by gautaz** [comment]
> _for any type of a_

Ah yes, now it makes sense.

So the easy way to treat a `String` as a [Foldable](https://github.com/fantasyland/fantasy-land#foldable) is to convert it to `Array Char` which means one can use `S.splitOn('')` and `S.joinWith('')` as conversion tools.

Thanks for the quick answer :-).
