### ISSUE TITLE
Missing, according to Wiki

### ISSUE THREAD

**Issue by blackxored** [sanctuary-js/sanctuary#505]
Rather than creating separate issues, I thought I would point out some of the most used things I miss from Ramda when coming to Sanctuary and hopefully hear about whether they're on the roadmap, been discussed, or should:

* `tap`: #504 
* `assocPath`: I use it all the time, ImmutableJS has a similar concept, so does Clojure and others.
* `cond`: Both Clojure and Ramda have it, and it's really helpful in replacing if statements and switch/case.
* `construct`/`invoker`/`partial`/`partialRight`: We have to deal with non-functional-friendly libraries and having helpers that would help us make functions like these would be really helpful.
* `into`.
* `isEmpty`, `isNil`, `propEq` and `pathEq` are really good with filters.
* `lift2/3` are missing from the Wiki in the Sanctuary side. 
* `memoize` Should I just give up on this? ;)
* `mergeDeepRight/mergeDeepLeft`.
* `pick`/`select-keys`.
* `reject` I know it's filter(negate(f)) but still.

Will update if you guys want me to.

EDIT: removed `ifElse`

**Comment by davidchambers** [comment]
>   - `assocPath`: I use it all the time, ImmutableJS has a similar concept, so does Clojure and others.

Ramda has ended up with a large number of functions for manipulating specific parts of a nested data structure. There's a great deal of duplication as a result of supporting lens-based and non-lens-based approaches. I would like to avoid this duplication by using lenses exclusively. The user will need to write slightly more code, but the code will me more powerful (since a lens can act as a getter, a setter, and an updater). Additionally, the API will have a small surface area, making it easy to learn.

>   - `cond`: Both Clojure and Ramda have it, and it's really helpful in replacing if statements and switch/case.

I added this function to Ramda several years ago, and have used it just a handful of times since. I do not find the function compelling. Consider the example from the [`R.cond`][1] documentation:

```javascript
var fn = R.cond([
  [R.equals(0),   R.always('water freezes at 0°C')],
  [R.equals(100), R.always('water boils at 100°C')],
  [R.T,           temp => 'nothing special happens at ' + temp + '°C']
]);
```

I would prefer to see the function written with nested ternary expressions:

```javascript
//    fn :: Number -> String
const fn = temp =>
  temp === 0    ? 'water freezes at 0°C' :
  temp === 100  ? 'water boils at 100°C' :
  /* otherwise */ 'nothing special happens at ' + temp + '°C';
```

>   - `construct`/`invoker`/`partial`/`partialRight`: We have to deal with non-functional-friendly libraries and having helpers that would help us make functions like these would be really helpful.

For me these functions contributed to an unhealthy obsession with point-free code. Consider this code I wrote several years ago:

```javascript
var getComments =
R.pipe(R.partialRight(esprima.parse, [{comment: true, loc: true}]),
       R.prop('comments'));
```

I rewrote the function during the weekend and find the result much clearer:

```javascript
function getComments(input) {
  return esprima.parse(input, {comment: true, loc: true}).comments;
}
```

>   - `into`.

Let's discuss this in #478.

>   - `isEmpty`, `isNil`, `propEq` and `pathEq` are really good with filters.

Could you provide a couple of examples of your use of `R.isEmpty`?

Instead of `isNil` I would use:

```javascript
x => x == null
```

Sanctuary is designed in such a way that it's rarely necessary to reference `null` or `undefined`. When it *is* necessary, I would prefer to see `x == null` so the offensive code stands out.

One could compose `S.isJust` and `S.toMaybe`, but a lambda is clearer.

Instead of `propEq`/`pathEq` I would use:

```javascript
o => S.equals ([1, 2, 3]) (o.x)
o => S.equals ([1, 2, 3]) (o.x.y.z)
```

One could compose `S.equals` and `S.prop`/`S.props`, of course, but a lambda is clearer.

>   - `lift2/3` are missing from the Wiki in the Sanctuary side.

The mapping is from Ramda functions to Sanctuary functions. A mapping from Sanctuary functions to Ramda functions would hopefully never be used. ;)

You're welcome to update the wiki as you see fit.

>   - `memoize` Should I just give up on this? ;)

Have you considered creating a dedicated npm package for this?

>   - `mergeDeepRight/mergeDeepLeft`.

I can't imagine providing these functions as they're not well defined, as whichever behaviour we were to choose would disappoint half of the potential users.

>   - `pick`/`select-keys`.

I'm 100% with you on this! I'd love to see this function:

```haskell
S.pick :: Array String -> StrMap a -> StrMap a
```

Would you like to submit a pull request?

>   - `reject` I know it's filter(negate(f)) but still.

This is coming in the next release. See #475 for details.


[1]: http://ramdajs.com/docs/#cond

**Comment by blackxored** [comment]
>  I would like to avoid this duplication by using lenses exclusively.

I wasn't aware lenses were coming, as I seem to recall an earlier discussion where I was told it wasn't on the roadmap (I might've asked for `lensPath`).
For some pipeline operations, if you're "treating mutable data as immutable" `assocPath` comes handy since your building an object up, it might not get the approval from really-functional programmers, but I've since this used quite a lot.

> I would prefer to see the function written with nested ternary expressions

IMHO most users wouldn't, and AirBnB's (and others) eslint would scream at us.
In addition, `cond` is most beneficial when the conditionals themselves are different. 

> For me these functions contributed to an unhealthy obsession with point-free code.
I agree, except we still have to deal with JS Date, String methods not in ramda, plus the plethora of frameworks/libraries out there. While I can concur we should probably write our own functions or not resort to point-free at all, it sticks out if you're doing this in the middle of a comp and defeats the purpose since I'm now thinking about what that code does and what the arguments are as opposed to being declarative about it.

> The mapping is from Ramda functions to Sanctuary functions. A mapping from Sanctuary functions to Ramda functions would hopefully never be used. ;)
I meant there's `lift2` and `lift3` on Sanctuary and the Sanctuary side for it it's different, I'm honestly not sure whether this was by design (they're indeed different), or something that needs to be added. I'd be happy to that if it's the latter.

> Could you provide a couple of examples of your use of R.isEmpty?
I use it a lot with arrays. I agree `isNil` is worthless if all your data is "safe" aka Sanctuary-safe, but unfortunately, it's not when you're transitioning. 

> Have you considered creating a dedicated npm package for this?
Oh dear, and here I was about to suggest `trampoline`. 😂 I don't see why `memoize` is any different from `curry`, `flip`, `lift` and other HOFs already present in the library.

> I can't imagine providing these functions as they're not well defined, as whichever behavior we were to choose would disappoint half of the potential users.
I'd be happy if we had to provide a combination function similar to how transducers work. No default behavior but the fact that we don't have to care about traversing anymore would be enough for me.

**Comment by davidchambers** [comment]
> if you're "treating mutable data as immutable" `assocPath` comes handy since your building an object up

I agree. At some point, though, we need to say no to handy functions. Currently `assocPath` is a handy function I don't think Sanctuary should provide, but I'm open to having my mind changed. :)

> `cond` is most beneficial when the conditionals themselves are different

What do you mean by this? Could you provide an example?

> there's `lift2` and `lift3` on […] the Sanctuary side

`R.lift` is a complex monstrosity, in my view. Sanctuary provides `S.map` for lifting unary functions, `S.lift2` for lifting binary functions, and `S.lift3` for lifting ternary functions.

> I use [`R.isEmpty`] a lot with arrays

Had you considered using `S.equals ([])` in such cases?

> I don't see why `memoize` is any different from […] other HOFs already present in the library

There are multiple approaches, each with pros and cons. If we serialize arguments as keys in a string map, we limit ourselves to serializable values. If we use an approach which handles every possible value we may end up with a comparison algorithm which is slower than the wrapped function. ;)

> I'd be happy if we had to provide a combination function similar to how transducers work. No default behavior but the fact that we don't have to care about traversing anymore would be enough for me.

I'd love to hear more about this in #478.
