### ISSUE TITLE
S.get and S.gets without first argument

### ISSUE THREAD

**Issue by daaaaa** [sanctuary-js/sanctuary#611]
Hello there, I'm relatively new at FP in JS and i'm finding this library quire useful.

I am a heavy Ramda user and two of the functions I use most are [`R.prop`](https://ramdajs.com/docs/#prop) and [`R.path`](https://ramdajs.com/docs/#path). 

What I really like about both of them is that they allow me to get a value in a safe way.
If the prop or the path is missing in the provided object, `undefined` is returned.

It would be perfect if:
1) the prop/path exists, a `Just(value)` is returned
2) the prop/path does not exists a `Nothing` is returned

Your library implements an `S.prop` and an `S.props` having a different behavior.
Indeed in case 1 the value is returned, while in case 2 an error is thrown.

So in your documentation it is suggested to use the `S.get`/`S.gets` functions to access a property/path of uncertain objects.
But in such a case the functions signature is different because I need - first of all - to provide a predicate.

Eventually I ended up to use a combination of `monet.js` and `ramda` to obtain a function satisfying point 1 and 2 of my previous list.
For example, this is a possible solution (where R is ramda and Maybe is from monet). 

```
const propMaybe = prop => R.pipe(
  R.prop(prop),
  Maybe.fromNull,
)
```

As I said at the beginning, I am quite new in the FP world, so I am sure I am missing the point. But wouldn't be useful a something like the function I described?

I think you have already something very similar that is `S.head`.

Thank you in advance for your answers.

**Comment by davidchambers** [comment]
Thank you for your thoughtful and courteous post, @daaaaa, and welcome to the community. :wave:

As you noted, [`S.prop`][1] and [`S.get`][2] serve different roles.

[`S.prop`][1] provides a convenient way to access values of record fields. Imagine we have this type:

```purescript
type User = { username :: String, email :: String }
```

We could trivially write accessor functions for the various fields:

```javascript
//    username :: User -> String
const username = user => user.username;

//    email :: User -> String
const email = user => user.email;
```

We could, though, use `S.prop ('email')` rather than the `email` accessor defined above. It is slightly noisier, but it would save us from writing and maintaining boilerplate for each of our record types.

[`S.get`][2] allows us to work with user input without trusting it. If an untrusted input is supposed to be an object with a Boolean `foo` property, we should not use `x.foo`. Even checking for the presence of the property is insufficient: the value may be of the wrong type, which could result in surprises due to type coercion. We should assert that the property exists and that its value is of the expected type:

```javascript
S.get (S.is ($.Boolean)) ('foo') (input)
```

This takes us from `input :: Any` to a value of type `Maybe Boolean`, resolving the uncertainty.

Sanctuary does not currently facilitate the common task of accessing a value of a string map by its key. Consider accessing a mapping from username to email address. `S.get (S.is ($.String))` works, but it should not be necessary to state the expected type if the string map is under our control. We could instead use `S.get (S.K (true))`, but this misbehaves if the key is `'valueOf'`, say, and the string map inherits from `Object.prototype`. Always remembering to use `Object.create (null)` rather than `{}` when creating a string map is unrealistic; I imagine many of my own uses of `S.get (S.K (true))` are unsafe. Additionally, `S.get (S.K (true))` is awkward to write and to read.

I propose the addition of a function for accessing values of a string map by key:

```haskell
S.??? :: String -> StrMap a -> Maybe a
```

I would appreciate suggestions for the name of this function. The function is related to [`S.insert`][3] and [`S.remove`][4] which are named after their Haskell equivalents, so `lookup` is a candidate. The function is also related to [`S.values`][5], so `value` offers internal consistency.

The function could be used in conjunction with [`S.chain`][6] to access a value of a nested string map:

```javascript
//    foo$bar :: StrMap (StrMap a) -> Maybe a
const foo$bar = S.compose (S.chain (S.??? ('bar'))) (S.??? ('foo'));
```

@daaaaa, would the proposed `String -> StrMap a -> Maybe a` function address your needs?


[1]: https://sanctuary.js.org/#prop
[2]: https://sanctuary.js.org/#get
[3]: https://sanctuary.js.org/#insert
[4]: https://sanctuary.js.org/#remove
[5]: https://sanctuary.js.org/#values
[6]: https://sanctuary.js.org/#chain
