### ISSUE TITLE
S.of(S.Maybe)(void 0) gives Just(undefined) instead of Nothing.

### ISSUE THREAD

**Issue by t1ger-0527** [sanctuary-js/sanctuary#651]
Hi masters!

I'm learning FP with this book [mostly-adequate-guide](https://mostly-adequate.gitbooks.io/mostly-adequate-guide/content/) and I'm using sanctuary as a real-world reference. I find having this well documented and nicely implemented library helps a lot! Thanks for developing such great project!

Regarding my question. Maybe I'm using it wrong, but is the value `Just(undefined)` by design? 

What is the proper way to convert an unsafe data (maybe from a remote endpoint) to `Nothing/Just` that we can pipe into functions safely?

**Comment by davidchambers** [comment]
Hello, @t1ger-0527. :wave:

> Maybe I'm using it wrong, but is the value `Just(undefined)` by design?

This is very much by design. The type of [`S.of`][1] is `Applicative f => TypeRep f -> a -> f a`. There are no constraints on `a`, which means we can replace it with any type we choose, even [`Undefined`][2].

[`S.head`][3] returns a value from which we can infer whether the input was empty:

```javascript
> S.head ([])
Nothing

> S.head ([undefined, undefined, undefined])
Just (undefined)
```

Were `null` and `undefined` to be treated specially we would lose this property. In general, special cases should be avoided. :)

> What is the proper way to convert an unsafe data (maybe from a remote endpoint) to `Nothing/Just` that we can pipe into functions safely?

Excellent question. Consider a value `xs` that we assume to be either `null`/`undefined` or an array of integers. We could convert this to a value of type `Maybe (Array Integer)` in a straightforward manner:

```javascript
xs == null ? S.Nothing : S.Just (xs)
```

Depending on our level of confidence in our assumption, the expression above may or may not be satisfactory. If we want to be *certain* that the result is of type `Maybe (Array Integer)`, we should specify a suitably demanding predicate:

```javascript
S.filter (S.is ($.Array ($.Integer))) (S.Just (xs))
```

In the expression above, `$` refers to the [sanctuary-def][4] module.

[`S.get`][5], [`S.gets`][6], and [`S.parseJson`][7] can also be of use when dealing with untrusted inputs.


[1]: https://sanctuary.js.org/#of
[2]: https://github.com/sanctuary-js/sanctuary-def#Undefined
[3]: https://sanctuary.js.org/#head
[4]: https://github.com/sanctuary-js/sanctuary-def
[5]: https://sanctuary.js.org/#get
[6]: https://sanctuary.js.org/#gets
[7]: https://sanctuary.js.org/#parseJson

**Comment by t1ger-0527** [comment]
@davidchambers Thanks for such quick and thoughtful reply! It solves my question perfectly! ❤️

**Comment by davidchambers** [comment]
You are welcome, @t1ger-0527. :)
