### ISSUE TITLE
Possible example bug

### ISSUE THREAD

**Issue by coodoo** [sanctuary-js/sanctuary#656]
Seemed the example for `S.concat` needs some update? For now it returned with errors.

```js
S.concat (Sum (18)) (Sum (24))
// Sum (42)
```

**Comment by davidchambers** [comment]
In which context are you seeing an error, @coodoo? On the [website][1]? In the REPL?


[1]: https://sanctuary.js.org/#concat

**Comment by coodoo** [comment]
I typed it out in my file and ran it, seemed Sum is missing and there’s no way to import it?

**Comment by davidchambers** [comment]
`Sum` is defined in [__test/internal/Sum.js__][1]. It is not exported, because it was only intended to be used in examples. You are welcome to use it, of course, but you would need to depend on the Git repository rather than the npm package.

[Gitter][2] is another good place for asking questions. :)


[1]: https://github.com/sanctuary-js/sanctuary/blob/v2.0.1/test/internal/Sum.js
[2]: https://gitter.im/sanctuary-js/sanctuary
