### ISSUE TITLE
Add "picks" to include certain key/value pairs from an object

### ISSUE THREAD

**Issue by Siilwyn** [sanctuary-js/sanctuary#701]
[Similar to R.pick](https://ramdajs.com/docs/#pick) it would be nice to have a function that achieves the same.

Something that does: `picks :: Array String -> a -> b`

**Comment by davidchambers** [comment]
Such a function could be used to filter a string map by keys, or to create one record from another.

Modern JavaScript syntax suffices if the keys or field names are static:

```javascript
> (({b, d}) => ({b, d})) ({a: 1, b: 2, c: 3, d: 4})
{b: 2, d: 4}
```

```javascript
> (({x, y}) => ({x, y})) ({x: 0, y: 0, color: '#000'})
{x: 0, y: 0}
```

I prefer `({x, y}) => ({x, y})` to `picks (['x', 'y'])` because `picks` is difficult to describe in a Hindley–Milner type system (one must resort to an approximation such as `Array String -> a -> b` or `Array String -> Object -> Object`).

What do you think, @Siilwyn? Do you often find yourself filtering string maps by dynamic keys?

**Comment by Siilwyn** [comment]
In most cases I'm filtering by static keys, I indeed often go with `({x, y}) => ({x, y})` however don't find it that nice to work with when the amount of keys and their length is long. In that case it often go multiline like:
```
({
  x,
  y,
  someLongKey,
}) =>
({
  x,
  y,
  someLongkey,
})
```

Which I don't find very readable and means if I change one of the keys I need to do it in two places.

**Comment by davidchambers** [comment]
Thank you for the proposal, @Siilwyn. Currently I do not think the proposed function belongs in the library.
